/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadenceToGoRouteImport } from './routes/cadence-to-go'
import { Route as CssToJsRouteImport } from './routes/css-to-js'
import { Route as CssToTailwindRouteImport } from './routes/css-to-tailwind'
import { Route as FlowToJavascriptRouteImport } from './routes/flow-to-javascript'
import { Route as FlowToTypescriptRouteImport } from './routes/flow-to-typescript'
import { Route as FlowToTypescriptDeclarationRouteImport } from './routes/flow-to-typescript-declaration'
import { Route as GraphqlToComponentsRouteImport } from './routes/graphql-to-components'
import { Route as GraphqlToFlowRouteImport } from './routes/graphql-to-flow'
import { Route as GraphqlToFragmentMatcherRouteImport } from './routes/graphql-to-fragment-matcher'
import { Route as GraphqlToIntrospectionJsonRouteImport } from './routes/graphql-to-introspection-json'
import { Route as GraphqlToJavaRouteImport } from './routes/graphql-to-java'
import { Route as GraphqlToResolversSignatureRouteImport } from './routes/graphql-to-resolvers-signature'
import { Route as GraphqlToSchemaAstRouteImport } from './routes/graphql-to-schema-ast'
import { Route as GraphqlToTypescriptRouteImport } from './routes/graphql-to-typescript'
import { Route as GraphqlToTypescriptMongodbRouteImport } from './routes/graphql-to-typescript-mongodb'
import { Route as HtmlToJsxRouteImport } from './routes/html-to-jsx'
import { Route as HtmlToPugRouteImport } from './routes/html-to-pug'
import { Route as JsObjectToJsonRouteImport } from './routes/js-object-to-json'
import { Route as JsObjectToTypescriptRouteImport } from './routes/js-object-to-typescript'
import { Route as JsonSchemaToOpenapiSchemaRouteImport } from './routes/json-schema-to-openapi-schema'
import { Route as JsonSchemaToProtobufRouteImport } from './routes/json-schema-to-protobuf'
import { Route as JsonSchemaToTsRouteImport } from './routes/json-schema-to-ts'
import { Route as JsonSchemaToTypescriptRouteImport } from './routes/json-schema-to-typescript'
import { Route as JsonSchemaToZodRouteImport } from './routes/json-schema-to-zod'
import { Route as JsonToBigQueryRouteImport } from './routes/json-to-big-query'
import { Route as JsonToFlowRouteImport } from './routes/json-to-flow'
import { Route as JsonToFlowTypesRouteImport } from './routes/json-to-flow-types'
import { Route as JsonToGoRouteImport } from './routes/json-to-go'
import { Route as JsonToGoBsonRouteImport } from './routes/json-to-go-bson'
import { Route as JsonToGraphqlRouteImport } from './routes/json-to-graphql'
import { Route as JsonToIoTsRouteImport } from './routes/json-to-io-ts'
import { Route as JsonToJavaRouteImport } from './routes/json-to-java'
import { Route as JsonToJsdocRouteImport } from './routes/json-to-jsdoc'
import { Route as JsonToJsonSchemaRouteImport } from './routes/json-to-json-schema'
import { Route as JsonToKotlinRouteImport } from './routes/json-to-kotlin'
import { Route as JsonToMobxStateTreeRouteImport } from './routes/json-to-mobx-state-tree'
import { Route as JsonToMongooseRouteImport } from './routes/json-to-mongoose'
import { Route as JsonToMysqlRouteImport } from './routes/json-to-mysql'
import { Route as JsonToProptypesRouteImport } from './routes/json-to-proptypes'
import { Route as JsonToRustSerdeRouteImport } from './routes/json-to-rust-serde'
import { Route as JsonToSarcasticRouteImport } from './routes/json-to-sarcastic'
import { Route as JsonToScalaCaseClassRouteImport } from './routes/json-to-scala-case-class'
import { Route as JsonToTomlRouteImport } from './routes/json-to-toml'
import { Route as JsonToTsInterfaceRouteImport } from './routes/json-to-ts-interface'
import { Route as JsonToTypescriptRouteImport } from './routes/json-to-typescript'
import { Route as JsonToYamlRouteImport } from './routes/json-to-yaml'
import { Route as JsonToZodRouteImport } from './routes/json-to-zod'
import { Route as JsonldToCompactedRouteImport } from './routes/jsonld-to-compacted'
import { Route as JsonldToExpandedRouteImport } from './routes/jsonld-to-expanded'
import { Route as JsonldToFlattenedRouteImport } from './routes/jsonld-to-flattened'
import { Route as JsonldToFramedRouteImport } from './routes/jsonld-to-framed'
import { Route as JsonldToNormalizedRouteImport } from './routes/jsonld-to-normalized'
import { Route as JsonldToNquadsRouteImport } from './routes/jsonld-to-nquads'
import { Route as MarkdownToHtmlRouteImport } from './routes/markdown-to-html'
import { Route as ObjectStylesToTemplateLiteralRouteImport } from './routes/object-styles-to-template-literal'
import { Route as SvgToJsxRouteImport } from './routes/svg-to-jsx'
import { Route as SvgToReactNativeRouteImport } from './routes/svg-to-react-native'
import { Route as TomlToJsonRouteImport } from './routes/toml-to-json'
import { Route as TomlToYamlRouteImport } from './routes/toml-to-yaml'
import { Route as TypescriptToFlowRouteImport } from './routes/typescript-to-flow'
import { Route as TypescriptToJavascriptRouteImport } from './routes/typescript-to-javascript'
import { Route as TypescriptToJsonSchemaRouteImport } from './routes/typescript-to-json-schema'
import { Route as TypescriptToTypescriptDeclarationRouteImport } from './routes/typescript-to-typescript-declaration'
import { Route as TypescriptToZodRouteImport } from './routes/typescript-to-zod'
import { Route as XmlToJsonRouteImport } from './routes/xml-to-json'
import { Route as YamlToJsonRouteImport } from './routes/yaml-to-json'
import { Route as YamlToTomlRouteImport } from './routes/yaml-to-toml'
import { Route as ApiFlowToJavascriptRouteImport } from './routes/api.flow-to-javascript'
import { Route as ApiFlowToTypescriptRouteImport } from './routes/api.flow-to-typescript'
import { Route as ApiHtmlToPugRouteImport } from './routes/api.html-to-pug'
import { Route as ApiJsonSchemaToOpenapiSchemaRouteImport } from './routes/api.json-schema-to-openapi-schema'
import { Route as ApiTypescriptToFlowRouteImport } from './routes/api.typescript-to-flow'
import { Route as ApiTypescriptToJavascriptRouteImport } from './routes/api.typescript-to-javascript'
import { Route as ApiTypescriptToJsonSchemaRouteImport } from './routes/api.typescript-to-json-schema'
import { Route as ApiTypescriptToZodRouteImport } from './routes/api.typescript-to-zod'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadenceToGoRoute = CadenceToGoRouteImport.update({
  id: '/cadence-to-go',
  path: '/cadence-to-go',
  getParentRoute: () => rootRouteImport,
} as any)
const CssToJsRoute = CssToJsRouteImport.update({
  id: '/css-to-js',
  path: '/css-to-js',
  getParentRoute: () => rootRouteImport,
} as any)
const CssToTailwindRoute = CssToTailwindRouteImport.update({
  id: '/css-to-tailwind',
  path: '/css-to-tailwind',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowToJavascriptRoute = FlowToJavascriptRouteImport.update({
  id: '/flow-to-javascript',
  path: '/flow-to-javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowToTypescriptRoute = FlowToTypescriptRouteImport.update({
  id: '/flow-to-typescript',
  path: '/flow-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowToTypescriptDeclarationRoute =
  FlowToTypescriptDeclarationRouteImport.update({
    id: '/flow-to-typescript-declaration',
    path: '/flow-to-typescript-declaration',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraphqlToComponentsRoute = GraphqlToComponentsRouteImport.update({
  id: '/graphql-to-components',
  path: '/graphql-to-components',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlToFlowRoute = GraphqlToFlowRouteImport.update({
  id: '/graphql-to-flow',
  path: '/graphql-to-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlToFragmentMatcherRoute =
  GraphqlToFragmentMatcherRouteImport.update({
    id: '/graphql-to-fragment-matcher',
    path: '/graphql-to-fragment-matcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraphqlToIntrospectionJsonRoute =
  GraphqlToIntrospectionJsonRouteImport.update({
    id: '/graphql-to-introspection-json',
    path: '/graphql-to-introspection-json',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraphqlToJavaRoute = GraphqlToJavaRouteImport.update({
  id: '/graphql-to-java',
  path: '/graphql-to-java',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlToResolversSignatureRoute =
  GraphqlToResolversSignatureRouteImport.update({
    id: '/graphql-to-resolvers-signature',
    path: '/graphql-to-resolvers-signature',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraphqlToSchemaAstRoute = GraphqlToSchemaAstRouteImport.update({
  id: '/graphql-to-schema-ast',
  path: '/graphql-to-schema-ast',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlToTypescriptRoute = GraphqlToTypescriptRouteImport.update({
  id: '/graphql-to-typescript',
  path: '/graphql-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlToTypescriptMongodbRoute =
  GraphqlToTypescriptMongodbRouteImport.update({
    id: '/graphql-to-typescript-mongodb',
    path: '/graphql-to-typescript-mongodb',
    getParentRoute: () => rootRouteImport,
  } as any)
const HtmlToJsxRoute = HtmlToJsxRouteImport.update({
  id: '/html-to-jsx',
  path: '/html-to-jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlToPugRoute = HtmlToPugRouteImport.update({
  id: '/html-to-pug',
  path: '/html-to-pug',
  getParentRoute: () => rootRouteImport,
} as any)
const JsObjectToJsonRoute = JsObjectToJsonRouteImport.update({
  id: '/js-object-to-json',
  path: '/js-object-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const JsObjectToTypescriptRoute = JsObjectToTypescriptRouteImport.update({
  id: '/js-object-to-typescript',
  path: '/js-object-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonSchemaToOpenapiSchemaRoute =
  JsonSchemaToOpenapiSchemaRouteImport.update({
    id: '/json-schema-to-openapi-schema',
    path: '/json-schema-to-openapi-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const JsonSchemaToProtobufRoute = JsonSchemaToProtobufRouteImport.update({
  id: '/json-schema-to-protobuf',
  path: '/json-schema-to-protobuf',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonSchemaToTsRoute = JsonSchemaToTsRouteImport.update({
  id: '/json-schema-to-ts',
  path: '/json-schema-to-ts',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonSchemaToTypescriptRoute = JsonSchemaToTypescriptRouteImport.update({
  id: '/json-schema-to-typescript',
  path: '/json-schema-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonSchemaToZodRoute = JsonSchemaToZodRouteImport.update({
  id: '/json-schema-to-zod',
  path: '/json-schema-to-zod',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToBigQueryRoute = JsonToBigQueryRouteImport.update({
  id: '/json-to-big-query',
  path: '/json-to-big-query',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToFlowRoute = JsonToFlowRouteImport.update({
  id: '/json-to-flow',
  path: '/json-to-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToFlowTypesRoute = JsonToFlowTypesRouteImport.update({
  id: '/json-to-flow-types',
  path: '/json-to-flow-types',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToGoRoute = JsonToGoRouteImport.update({
  id: '/json-to-go',
  path: '/json-to-go',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToGoBsonRoute = JsonToGoBsonRouteImport.update({
  id: '/json-to-go-bson',
  path: '/json-to-go-bson',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToGraphqlRoute = JsonToGraphqlRouteImport.update({
  id: '/json-to-graphql',
  path: '/json-to-graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToIoTsRoute = JsonToIoTsRouteImport.update({
  id: '/json-to-io-ts',
  path: '/json-to-io-ts',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToJavaRoute = JsonToJavaRouteImport.update({
  id: '/json-to-java',
  path: '/json-to-java',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToJsdocRoute = JsonToJsdocRouteImport.update({
  id: '/json-to-jsdoc',
  path: '/json-to-jsdoc',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToJsonSchemaRoute = JsonToJsonSchemaRouteImport.update({
  id: '/json-to-json-schema',
  path: '/json-to-json-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToKotlinRoute = JsonToKotlinRouteImport.update({
  id: '/json-to-kotlin',
  path: '/json-to-kotlin',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToMobxStateTreeRoute = JsonToMobxStateTreeRouteImport.update({
  id: '/json-to-mobx-state-tree',
  path: '/json-to-mobx-state-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToMongooseRoute = JsonToMongooseRouteImport.update({
  id: '/json-to-mongoose',
  path: '/json-to-mongoose',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToMysqlRoute = JsonToMysqlRouteImport.update({
  id: '/json-to-mysql',
  path: '/json-to-mysql',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToProptypesRoute = JsonToProptypesRouteImport.update({
  id: '/json-to-proptypes',
  path: '/json-to-proptypes',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToRustSerdeRoute = JsonToRustSerdeRouteImport.update({
  id: '/json-to-rust-serde',
  path: '/json-to-rust-serde',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToSarcasticRoute = JsonToSarcasticRouteImport.update({
  id: '/json-to-sarcastic',
  path: '/json-to-sarcastic',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToScalaCaseClassRoute = JsonToScalaCaseClassRouteImport.update({
  id: '/json-to-scala-case-class',
  path: '/json-to-scala-case-class',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTomlRoute = JsonToTomlRouteImport.update({
  id: '/json-to-toml',
  path: '/json-to-toml',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTsInterfaceRoute = JsonToTsInterfaceRouteImport.update({
  id: '/json-to-ts-interface',
  path: '/json-to-ts-interface',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTypescriptRoute = JsonToTypescriptRouteImport.update({
  id: '/json-to-typescript',
  path: '/json-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToYamlRoute = JsonToYamlRouteImport.update({
  id: '/json-to-yaml',
  path: '/json-to-yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToZodRoute = JsonToZodRouteImport.update({
  id: '/json-to-zod',
  path: '/json-to-zod',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToCompactedRoute = JsonldToCompactedRouteImport.update({
  id: '/jsonld-to-compacted',
  path: '/jsonld-to-compacted',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToExpandedRoute = JsonldToExpandedRouteImport.update({
  id: '/jsonld-to-expanded',
  path: '/jsonld-to-expanded',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToFlattenedRoute = JsonldToFlattenedRouteImport.update({
  id: '/jsonld-to-flattened',
  path: '/jsonld-to-flattened',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToFramedRoute = JsonldToFramedRouteImport.update({
  id: '/jsonld-to-framed',
  path: '/jsonld-to-framed',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToNormalizedRoute = JsonldToNormalizedRouteImport.update({
  id: '/jsonld-to-normalized',
  path: '/jsonld-to-normalized',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonldToNquadsRoute = JsonldToNquadsRouteImport.update({
  id: '/jsonld-to-nquads',
  path: '/jsonld-to-nquads',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownToHtmlRoute = MarkdownToHtmlRouteImport.update({
  id: '/markdown-to-html',
  path: '/markdown-to-html',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectStylesToTemplateLiteralRoute =
  ObjectStylesToTemplateLiteralRouteImport.update({
    id: '/object-styles-to-template-literal',
    path: '/object-styles-to-template-literal',
    getParentRoute: () => rootRouteImport,
  } as any)
const SvgToJsxRoute = SvgToJsxRouteImport.update({
  id: '/svg-to-jsx',
  path: '/svg-to-jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgToReactNativeRoute = SvgToReactNativeRouteImport.update({
  id: '/svg-to-react-native',
  path: '/svg-to-react-native',
  getParentRoute: () => rootRouteImport,
} as any)
const TomlToJsonRoute = TomlToJsonRouteImport.update({
  id: '/toml-to-json',
  path: '/toml-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const TomlToYamlRoute = TomlToYamlRouteImport.update({
  id: '/toml-to-yaml',
  path: '/toml-to-yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const TypescriptToFlowRoute = TypescriptToFlowRouteImport.update({
  id: '/typescript-to-flow',
  path: '/typescript-to-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const TypescriptToJavascriptRoute = TypescriptToJavascriptRouteImport.update({
  id: '/typescript-to-javascript',
  path: '/typescript-to-javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const TypescriptToJsonSchemaRoute = TypescriptToJsonSchemaRouteImport.update({
  id: '/typescript-to-json-schema',
  path: '/typescript-to-json-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const TypescriptToTypescriptDeclarationRoute =
  TypescriptToTypescriptDeclarationRouteImport.update({
    id: '/typescript-to-typescript-declaration',
    path: '/typescript-to-typescript-declaration',
    getParentRoute: () => rootRouteImport,
  } as any)
const TypescriptToZodRoute = TypescriptToZodRouteImport.update({
  id: '/typescript-to-zod',
  path: '/typescript-to-zod',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlToJsonRoute = XmlToJsonRouteImport.update({
  id: '/xml-to-json',
  path: '/xml-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const YamlToJsonRoute = YamlToJsonRouteImport.update({
  id: '/yaml-to-json',
  path: '/yaml-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const YamlToTomlRoute = YamlToTomlRouteImport.update({
  id: '/yaml-to-toml',
  path: '/yaml-to-toml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowToJavascriptRoute = ApiFlowToJavascriptRouteImport.update({
  id: '/api/flow-to-javascript',
  path: '/api/flow-to-javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowToTypescriptRoute = ApiFlowToTypescriptRouteImport.update({
  id: '/api/flow-to-typescript',
  path: '/api/flow-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHtmlToPugRoute = ApiHtmlToPugRouteImport.update({
  id: '/api/html-to-pug',
  path: '/api/html-to-pug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJsonSchemaToOpenapiSchemaRoute =
  ApiJsonSchemaToOpenapiSchemaRouteImport.update({
    id: '/api/json-schema-to-openapi-schema',
    path: '/api/json-schema-to-openapi-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTypescriptToFlowRoute = ApiTypescriptToFlowRouteImport.update({
  id: '/api/typescript-to-flow',
  path: '/api/typescript-to-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTypescriptToJavascriptRoute =
  ApiTypescriptToJavascriptRouteImport.update({
    id: '/api/typescript-to-javascript',
    path: '/api/typescript-to-javascript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTypescriptToJsonSchemaRoute =
  ApiTypescriptToJsonSchemaRouteImport.update({
    id: '/api/typescript-to-json-schema',
    path: '/api/typescript-to-json-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTypescriptToZodRoute = ApiTypescriptToZodRouteImport.update({
  id: '/api/typescript-to-zod',
  path: '/api/typescript-to-zod',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadence-to-go': typeof CadenceToGoRoute
  '/css-to-js': typeof CssToJsRoute
  '/css-to-tailwind': typeof CssToTailwindRoute
  '/flow-to-javascript': typeof FlowToJavascriptRoute
  '/flow-to-typescript': typeof FlowToTypescriptRoute
  '/flow-to-typescript-declaration': typeof FlowToTypescriptDeclarationRoute
  '/graphql-to-components': typeof GraphqlToComponentsRoute
  '/graphql-to-flow': typeof GraphqlToFlowRoute
  '/graphql-to-fragment-matcher': typeof GraphqlToFragmentMatcherRoute
  '/graphql-to-introspection-json': typeof GraphqlToIntrospectionJsonRoute
  '/graphql-to-java': typeof GraphqlToJavaRoute
  '/graphql-to-resolvers-signature': typeof GraphqlToResolversSignatureRoute
  '/graphql-to-schema-ast': typeof GraphqlToSchemaAstRoute
  '/graphql-to-typescript': typeof GraphqlToTypescriptRoute
  '/graphql-to-typescript-mongodb': typeof GraphqlToTypescriptMongodbRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/html-to-pug': typeof HtmlToPugRoute
  '/js-object-to-json': typeof JsObjectToJsonRoute
  '/js-object-to-typescript': typeof JsObjectToTypescriptRoute
  '/json-schema-to-openapi-schema': typeof JsonSchemaToOpenapiSchemaRoute
  '/json-schema-to-protobuf': typeof JsonSchemaToProtobufRoute
  '/json-schema-to-ts': typeof JsonSchemaToTsRoute
  '/json-schema-to-typescript': typeof JsonSchemaToTypescriptRoute
  '/json-schema-to-zod': typeof JsonSchemaToZodRoute
  '/json-to-big-query': typeof JsonToBigQueryRoute
  '/json-to-flow': typeof JsonToFlowRoute
  '/json-to-flow-types': typeof JsonToFlowTypesRoute
  '/json-to-go': typeof JsonToGoRoute
  '/json-to-go-bson': typeof JsonToGoBsonRoute
  '/json-to-graphql': typeof JsonToGraphqlRoute
  '/json-to-io-ts': typeof JsonToIoTsRoute
  '/json-to-java': typeof JsonToJavaRoute
  '/json-to-jsdoc': typeof JsonToJsdocRoute
  '/json-to-json-schema': typeof JsonToJsonSchemaRoute
  '/json-to-kotlin': typeof JsonToKotlinRoute
  '/json-to-mobx-state-tree': typeof JsonToMobxStateTreeRoute
  '/json-to-mongoose': typeof JsonToMongooseRoute
  '/json-to-mysql': typeof JsonToMysqlRoute
  '/json-to-proptypes': typeof JsonToProptypesRoute
  '/json-to-rust-serde': typeof JsonToRustSerdeRoute
  '/json-to-sarcastic': typeof JsonToSarcasticRoute
  '/json-to-scala-case-class': typeof JsonToScalaCaseClassRoute
  '/json-to-toml': typeof JsonToTomlRoute
  '/json-to-ts-interface': typeof JsonToTsInterfaceRoute
  '/json-to-typescript': typeof JsonToTypescriptRoute
  '/json-to-yaml': typeof JsonToYamlRoute
  '/json-to-zod': typeof JsonToZodRoute
  '/jsonld-to-compacted': typeof JsonldToCompactedRoute
  '/jsonld-to-expanded': typeof JsonldToExpandedRoute
  '/jsonld-to-flattened': typeof JsonldToFlattenedRoute
  '/jsonld-to-framed': typeof JsonldToFramedRoute
  '/jsonld-to-normalized': typeof JsonldToNormalizedRoute
  '/jsonld-to-nquads': typeof JsonldToNquadsRoute
  '/markdown-to-html': typeof MarkdownToHtmlRoute
  '/object-styles-to-template-literal': typeof ObjectStylesToTemplateLiteralRoute
  '/svg-to-jsx': typeof SvgToJsxRoute
  '/svg-to-react-native': typeof SvgToReactNativeRoute
  '/toml-to-json': typeof TomlToJsonRoute
  '/toml-to-yaml': typeof TomlToYamlRoute
  '/typescript-to-flow': typeof TypescriptToFlowRoute
  '/typescript-to-javascript': typeof TypescriptToJavascriptRoute
  '/typescript-to-json-schema': typeof TypescriptToJsonSchemaRoute
  '/typescript-to-typescript-declaration': typeof TypescriptToTypescriptDeclarationRoute
  '/typescript-to-zod': typeof TypescriptToZodRoute
  '/xml-to-json': typeof XmlToJsonRoute
  '/yaml-to-json': typeof YamlToJsonRoute
  '/yaml-to-toml': typeof YamlToTomlRoute
  '/api/flow-to-javascript': typeof ApiFlowToJavascriptRoute
  '/api/flow-to-typescript': typeof ApiFlowToTypescriptRoute
  '/api/html-to-pug': typeof ApiHtmlToPugRoute
  '/api/json-schema-to-openapi-schema': typeof ApiJsonSchemaToOpenapiSchemaRoute
  '/api/typescript-to-flow': typeof ApiTypescriptToFlowRoute
  '/api/typescript-to-javascript': typeof ApiTypescriptToJavascriptRoute
  '/api/typescript-to-json-schema': typeof ApiTypescriptToJsonSchemaRoute
  '/api/typescript-to-zod': typeof ApiTypescriptToZodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadence-to-go': typeof CadenceToGoRoute
  '/css-to-js': typeof CssToJsRoute
  '/css-to-tailwind': typeof CssToTailwindRoute
  '/flow-to-javascript': typeof FlowToJavascriptRoute
  '/flow-to-typescript': typeof FlowToTypescriptRoute
  '/flow-to-typescript-declaration': typeof FlowToTypescriptDeclarationRoute
  '/graphql-to-components': typeof GraphqlToComponentsRoute
  '/graphql-to-flow': typeof GraphqlToFlowRoute
  '/graphql-to-fragment-matcher': typeof GraphqlToFragmentMatcherRoute
  '/graphql-to-introspection-json': typeof GraphqlToIntrospectionJsonRoute
  '/graphql-to-java': typeof GraphqlToJavaRoute
  '/graphql-to-resolvers-signature': typeof GraphqlToResolversSignatureRoute
  '/graphql-to-schema-ast': typeof GraphqlToSchemaAstRoute
  '/graphql-to-typescript': typeof GraphqlToTypescriptRoute
  '/graphql-to-typescript-mongodb': typeof GraphqlToTypescriptMongodbRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/html-to-pug': typeof HtmlToPugRoute
  '/js-object-to-json': typeof JsObjectToJsonRoute
  '/js-object-to-typescript': typeof JsObjectToTypescriptRoute
  '/json-schema-to-openapi-schema': typeof JsonSchemaToOpenapiSchemaRoute
  '/json-schema-to-protobuf': typeof JsonSchemaToProtobufRoute
  '/json-schema-to-ts': typeof JsonSchemaToTsRoute
  '/json-schema-to-typescript': typeof JsonSchemaToTypescriptRoute
  '/json-schema-to-zod': typeof JsonSchemaToZodRoute
  '/json-to-big-query': typeof JsonToBigQueryRoute
  '/json-to-flow': typeof JsonToFlowRoute
  '/json-to-flow-types': typeof JsonToFlowTypesRoute
  '/json-to-go': typeof JsonToGoRoute
  '/json-to-go-bson': typeof JsonToGoBsonRoute
  '/json-to-graphql': typeof JsonToGraphqlRoute
  '/json-to-io-ts': typeof JsonToIoTsRoute
  '/json-to-java': typeof JsonToJavaRoute
  '/json-to-jsdoc': typeof JsonToJsdocRoute
  '/json-to-json-schema': typeof JsonToJsonSchemaRoute
  '/json-to-kotlin': typeof JsonToKotlinRoute
  '/json-to-mobx-state-tree': typeof JsonToMobxStateTreeRoute
  '/json-to-mongoose': typeof JsonToMongooseRoute
  '/json-to-mysql': typeof JsonToMysqlRoute
  '/json-to-proptypes': typeof JsonToProptypesRoute
  '/json-to-rust-serde': typeof JsonToRustSerdeRoute
  '/json-to-sarcastic': typeof JsonToSarcasticRoute
  '/json-to-scala-case-class': typeof JsonToScalaCaseClassRoute
  '/json-to-toml': typeof JsonToTomlRoute
  '/json-to-ts-interface': typeof JsonToTsInterfaceRoute
  '/json-to-typescript': typeof JsonToTypescriptRoute
  '/json-to-yaml': typeof JsonToYamlRoute
  '/json-to-zod': typeof JsonToZodRoute
  '/jsonld-to-compacted': typeof JsonldToCompactedRoute
  '/jsonld-to-expanded': typeof JsonldToExpandedRoute
  '/jsonld-to-flattened': typeof JsonldToFlattenedRoute
  '/jsonld-to-framed': typeof JsonldToFramedRoute
  '/jsonld-to-normalized': typeof JsonldToNormalizedRoute
  '/jsonld-to-nquads': typeof JsonldToNquadsRoute
  '/markdown-to-html': typeof MarkdownToHtmlRoute
  '/object-styles-to-template-literal': typeof ObjectStylesToTemplateLiteralRoute
  '/svg-to-jsx': typeof SvgToJsxRoute
  '/svg-to-react-native': typeof SvgToReactNativeRoute
  '/toml-to-json': typeof TomlToJsonRoute
  '/toml-to-yaml': typeof TomlToYamlRoute
  '/typescript-to-flow': typeof TypescriptToFlowRoute
  '/typescript-to-javascript': typeof TypescriptToJavascriptRoute
  '/typescript-to-json-schema': typeof TypescriptToJsonSchemaRoute
  '/typescript-to-typescript-declaration': typeof TypescriptToTypescriptDeclarationRoute
  '/typescript-to-zod': typeof TypescriptToZodRoute
  '/xml-to-json': typeof XmlToJsonRoute
  '/yaml-to-json': typeof YamlToJsonRoute
  '/yaml-to-toml': typeof YamlToTomlRoute
  '/api/flow-to-javascript': typeof ApiFlowToJavascriptRoute
  '/api/flow-to-typescript': typeof ApiFlowToTypescriptRoute
  '/api/html-to-pug': typeof ApiHtmlToPugRoute
  '/api/json-schema-to-openapi-schema': typeof ApiJsonSchemaToOpenapiSchemaRoute
  '/api/typescript-to-flow': typeof ApiTypescriptToFlowRoute
  '/api/typescript-to-javascript': typeof ApiTypescriptToJavascriptRoute
  '/api/typescript-to-json-schema': typeof ApiTypescriptToJsonSchemaRoute
  '/api/typescript-to-zod': typeof ApiTypescriptToZodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadence-to-go': typeof CadenceToGoRoute
  '/css-to-js': typeof CssToJsRoute
  '/css-to-tailwind': typeof CssToTailwindRoute
  '/flow-to-javascript': typeof FlowToJavascriptRoute
  '/flow-to-typescript': typeof FlowToTypescriptRoute
  '/flow-to-typescript-declaration': typeof FlowToTypescriptDeclarationRoute
  '/graphql-to-components': typeof GraphqlToComponentsRoute
  '/graphql-to-flow': typeof GraphqlToFlowRoute
  '/graphql-to-fragment-matcher': typeof GraphqlToFragmentMatcherRoute
  '/graphql-to-introspection-json': typeof GraphqlToIntrospectionJsonRoute
  '/graphql-to-java': typeof GraphqlToJavaRoute
  '/graphql-to-resolvers-signature': typeof GraphqlToResolversSignatureRoute
  '/graphql-to-schema-ast': typeof GraphqlToSchemaAstRoute
  '/graphql-to-typescript': typeof GraphqlToTypescriptRoute
  '/graphql-to-typescript-mongodb': typeof GraphqlToTypescriptMongodbRoute
  '/html-to-jsx': typeof HtmlToJsxRoute
  '/html-to-pug': typeof HtmlToPugRoute
  '/js-object-to-json': typeof JsObjectToJsonRoute
  '/js-object-to-typescript': typeof JsObjectToTypescriptRoute
  '/json-schema-to-openapi-schema': typeof JsonSchemaToOpenapiSchemaRoute
  '/json-schema-to-protobuf': typeof JsonSchemaToProtobufRoute
  '/json-schema-to-ts': typeof JsonSchemaToTsRoute
  '/json-schema-to-typescript': typeof JsonSchemaToTypescriptRoute
  '/json-schema-to-zod': typeof JsonSchemaToZodRoute
  '/json-to-big-query': typeof JsonToBigQueryRoute
  '/json-to-flow': typeof JsonToFlowRoute
  '/json-to-flow-types': typeof JsonToFlowTypesRoute
  '/json-to-go': typeof JsonToGoRoute
  '/json-to-go-bson': typeof JsonToGoBsonRoute
  '/json-to-graphql': typeof JsonToGraphqlRoute
  '/json-to-io-ts': typeof JsonToIoTsRoute
  '/json-to-java': typeof JsonToJavaRoute
  '/json-to-jsdoc': typeof JsonToJsdocRoute
  '/json-to-json-schema': typeof JsonToJsonSchemaRoute
  '/json-to-kotlin': typeof JsonToKotlinRoute
  '/json-to-mobx-state-tree': typeof JsonToMobxStateTreeRoute
  '/json-to-mongoose': typeof JsonToMongooseRoute
  '/json-to-mysql': typeof JsonToMysqlRoute
  '/json-to-proptypes': typeof JsonToProptypesRoute
  '/json-to-rust-serde': typeof JsonToRustSerdeRoute
  '/json-to-sarcastic': typeof JsonToSarcasticRoute
  '/json-to-scala-case-class': typeof JsonToScalaCaseClassRoute
  '/json-to-toml': typeof JsonToTomlRoute
  '/json-to-ts-interface': typeof JsonToTsInterfaceRoute
  '/json-to-typescript': typeof JsonToTypescriptRoute
  '/json-to-yaml': typeof JsonToYamlRoute
  '/json-to-zod': typeof JsonToZodRoute
  '/jsonld-to-compacted': typeof JsonldToCompactedRoute
  '/jsonld-to-expanded': typeof JsonldToExpandedRoute
  '/jsonld-to-flattened': typeof JsonldToFlattenedRoute
  '/jsonld-to-framed': typeof JsonldToFramedRoute
  '/jsonld-to-normalized': typeof JsonldToNormalizedRoute
  '/jsonld-to-nquads': typeof JsonldToNquadsRoute
  '/markdown-to-html': typeof MarkdownToHtmlRoute
  '/object-styles-to-template-literal': typeof ObjectStylesToTemplateLiteralRoute
  '/svg-to-jsx': typeof SvgToJsxRoute
  '/svg-to-react-native': typeof SvgToReactNativeRoute
  '/toml-to-json': typeof TomlToJsonRoute
  '/toml-to-yaml': typeof TomlToYamlRoute
  '/typescript-to-flow': typeof TypescriptToFlowRoute
  '/typescript-to-javascript': typeof TypescriptToJavascriptRoute
  '/typescript-to-json-schema': typeof TypescriptToJsonSchemaRoute
  '/typescript-to-typescript-declaration': typeof TypescriptToTypescriptDeclarationRoute
  '/typescript-to-zod': typeof TypescriptToZodRoute
  '/xml-to-json': typeof XmlToJsonRoute
  '/yaml-to-json': typeof YamlToJsonRoute
  '/yaml-to-toml': typeof YamlToTomlRoute
  '/api/flow-to-javascript': typeof ApiFlowToJavascriptRoute
  '/api/flow-to-typescript': typeof ApiFlowToTypescriptRoute
  '/api/html-to-pug': typeof ApiHtmlToPugRoute
  '/api/json-schema-to-openapi-schema': typeof ApiJsonSchemaToOpenapiSchemaRoute
  '/api/typescript-to-flow': typeof ApiTypescriptToFlowRoute
  '/api/typescript-to-javascript': typeof ApiTypescriptToJavascriptRoute
  '/api/typescript-to-json-schema': typeof ApiTypescriptToJsonSchemaRoute
  '/api/typescript-to-zod': typeof ApiTypescriptToZodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadence-to-go'
    | '/css-to-js'
    | '/css-to-tailwind'
    | '/flow-to-javascript'
    | '/flow-to-typescript'
    | '/flow-to-typescript-declaration'
    | '/graphql-to-components'
    | '/graphql-to-flow'
    | '/graphql-to-fragment-matcher'
    | '/graphql-to-introspection-json'
    | '/graphql-to-java'
    | '/graphql-to-resolvers-signature'
    | '/graphql-to-schema-ast'
    | '/graphql-to-typescript'
    | '/graphql-to-typescript-mongodb'
    | '/html-to-jsx'
    | '/html-to-pug'
    | '/js-object-to-json'
    | '/js-object-to-typescript'
    | '/json-schema-to-openapi-schema'
    | '/json-schema-to-protobuf'
    | '/json-schema-to-ts'
    | '/json-schema-to-typescript'
    | '/json-schema-to-zod'
    | '/json-to-big-query'
    | '/json-to-flow'
    | '/json-to-flow-types'
    | '/json-to-go'
    | '/json-to-go-bson'
    | '/json-to-graphql'
    | '/json-to-io-ts'
    | '/json-to-java'
    | '/json-to-jsdoc'
    | '/json-to-json-schema'
    | '/json-to-kotlin'
    | '/json-to-mobx-state-tree'
    | '/json-to-mongoose'
    | '/json-to-mysql'
    | '/json-to-proptypes'
    | '/json-to-rust-serde'
    | '/json-to-sarcastic'
    | '/json-to-scala-case-class'
    | '/json-to-toml'
    | '/json-to-ts-interface'
    | '/json-to-typescript'
    | '/json-to-yaml'
    | '/json-to-zod'
    | '/jsonld-to-compacted'
    | '/jsonld-to-expanded'
    | '/jsonld-to-flattened'
    | '/jsonld-to-framed'
    | '/jsonld-to-normalized'
    | '/jsonld-to-nquads'
    | '/markdown-to-html'
    | '/object-styles-to-template-literal'
    | '/svg-to-jsx'
    | '/svg-to-react-native'
    | '/toml-to-json'
    | '/toml-to-yaml'
    | '/typescript-to-flow'
    | '/typescript-to-javascript'
    | '/typescript-to-json-schema'
    | '/typescript-to-typescript-declaration'
    | '/typescript-to-zod'
    | '/xml-to-json'
    | '/yaml-to-json'
    | '/yaml-to-toml'
    | '/api/flow-to-javascript'
    | '/api/flow-to-typescript'
    | '/api/html-to-pug'
    | '/api/json-schema-to-openapi-schema'
    | '/api/typescript-to-flow'
    | '/api/typescript-to-javascript'
    | '/api/typescript-to-json-schema'
    | '/api/typescript-to-zod'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadence-to-go'
    | '/css-to-js'
    | '/css-to-tailwind'
    | '/flow-to-javascript'
    | '/flow-to-typescript'
    | '/flow-to-typescript-declaration'
    | '/graphql-to-components'
    | '/graphql-to-flow'
    | '/graphql-to-fragment-matcher'
    | '/graphql-to-introspection-json'
    | '/graphql-to-java'
    | '/graphql-to-resolvers-signature'
    | '/graphql-to-schema-ast'
    | '/graphql-to-typescript'
    | '/graphql-to-typescript-mongodb'
    | '/html-to-jsx'
    | '/html-to-pug'
    | '/js-object-to-json'
    | '/js-object-to-typescript'
    | '/json-schema-to-openapi-schema'
    | '/json-schema-to-protobuf'
    | '/json-schema-to-ts'
    | '/json-schema-to-typescript'
    | '/json-schema-to-zod'
    | '/json-to-big-query'
    | '/json-to-flow'
    | '/json-to-flow-types'
    | '/json-to-go'
    | '/json-to-go-bson'
    | '/json-to-graphql'
    | '/json-to-io-ts'
    | '/json-to-java'
    | '/json-to-jsdoc'
    | '/json-to-json-schema'
    | '/json-to-kotlin'
    | '/json-to-mobx-state-tree'
    | '/json-to-mongoose'
    | '/json-to-mysql'
    | '/json-to-proptypes'
    | '/json-to-rust-serde'
    | '/json-to-sarcastic'
    | '/json-to-scala-case-class'
    | '/json-to-toml'
    | '/json-to-ts-interface'
    | '/json-to-typescript'
    | '/json-to-yaml'
    | '/json-to-zod'
    | '/jsonld-to-compacted'
    | '/jsonld-to-expanded'
    | '/jsonld-to-flattened'
    | '/jsonld-to-framed'
    | '/jsonld-to-normalized'
    | '/jsonld-to-nquads'
    | '/markdown-to-html'
    | '/object-styles-to-template-literal'
    | '/svg-to-jsx'
    | '/svg-to-react-native'
    | '/toml-to-json'
    | '/toml-to-yaml'
    | '/typescript-to-flow'
    | '/typescript-to-javascript'
    | '/typescript-to-json-schema'
    | '/typescript-to-typescript-declaration'
    | '/typescript-to-zod'
    | '/xml-to-json'
    | '/yaml-to-json'
    | '/yaml-to-toml'
    | '/api/flow-to-javascript'
    | '/api/flow-to-typescript'
    | '/api/html-to-pug'
    | '/api/json-schema-to-openapi-schema'
    | '/api/typescript-to-flow'
    | '/api/typescript-to-javascript'
    | '/api/typescript-to-json-schema'
    | '/api/typescript-to-zod'
  id:
    | '__root__'
    | '/'
    | '/cadence-to-go'
    | '/css-to-js'
    | '/css-to-tailwind'
    | '/flow-to-javascript'
    | '/flow-to-typescript'
    | '/flow-to-typescript-declaration'
    | '/graphql-to-components'
    | '/graphql-to-flow'
    | '/graphql-to-fragment-matcher'
    | '/graphql-to-introspection-json'
    | '/graphql-to-java'
    | '/graphql-to-resolvers-signature'
    | '/graphql-to-schema-ast'
    | '/graphql-to-typescript'
    | '/graphql-to-typescript-mongodb'
    | '/html-to-jsx'
    | '/html-to-pug'
    | '/js-object-to-json'
    | '/js-object-to-typescript'
    | '/json-schema-to-openapi-schema'
    | '/json-schema-to-protobuf'
    | '/json-schema-to-ts'
    | '/json-schema-to-typescript'
    | '/json-schema-to-zod'
    | '/json-to-big-query'
    | '/json-to-flow'
    | '/json-to-flow-types'
    | '/json-to-go'
    | '/json-to-go-bson'
    | '/json-to-graphql'
    | '/json-to-io-ts'
    | '/json-to-java'
    | '/json-to-jsdoc'
    | '/json-to-json-schema'
    | '/json-to-kotlin'
    | '/json-to-mobx-state-tree'
    | '/json-to-mongoose'
    | '/json-to-mysql'
    | '/json-to-proptypes'
    | '/json-to-rust-serde'
    | '/json-to-sarcastic'
    | '/json-to-scala-case-class'
    | '/json-to-toml'
    | '/json-to-ts-interface'
    | '/json-to-typescript'
    | '/json-to-yaml'
    | '/json-to-zod'
    | '/jsonld-to-compacted'
    | '/jsonld-to-expanded'
    | '/jsonld-to-flattened'
    | '/jsonld-to-framed'
    | '/jsonld-to-normalized'
    | '/jsonld-to-nquads'
    | '/markdown-to-html'
    | '/object-styles-to-template-literal'
    | '/svg-to-jsx'
    | '/svg-to-react-native'
    | '/toml-to-json'
    | '/toml-to-yaml'
    | '/typescript-to-flow'
    | '/typescript-to-javascript'
    | '/typescript-to-json-schema'
    | '/typescript-to-typescript-declaration'
    | '/typescript-to-zod'
    | '/xml-to-json'
    | '/yaml-to-json'
    | '/yaml-to-toml'
    | '/api/flow-to-javascript'
    | '/api/flow-to-typescript'
    | '/api/html-to-pug'
    | '/api/json-schema-to-openapi-schema'
    | '/api/typescript-to-flow'
    | '/api/typescript-to-javascript'
    | '/api/typescript-to-json-schema'
    | '/api/typescript-to-zod'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadenceToGoRoute: typeof CadenceToGoRoute
  CssToJsRoute: typeof CssToJsRoute
  CssToTailwindRoute: typeof CssToTailwindRoute
  FlowToJavascriptRoute: typeof FlowToJavascriptRoute
  FlowToTypescriptRoute: typeof FlowToTypescriptRoute
  FlowToTypescriptDeclarationRoute: typeof FlowToTypescriptDeclarationRoute
  GraphqlToComponentsRoute: typeof GraphqlToComponentsRoute
  GraphqlToFlowRoute: typeof GraphqlToFlowRoute
  GraphqlToFragmentMatcherRoute: typeof GraphqlToFragmentMatcherRoute
  GraphqlToIntrospectionJsonRoute: typeof GraphqlToIntrospectionJsonRoute
  GraphqlToJavaRoute: typeof GraphqlToJavaRoute
  GraphqlToResolversSignatureRoute: typeof GraphqlToResolversSignatureRoute
  GraphqlToSchemaAstRoute: typeof GraphqlToSchemaAstRoute
  GraphqlToTypescriptRoute: typeof GraphqlToTypescriptRoute
  GraphqlToTypescriptMongodbRoute: typeof GraphqlToTypescriptMongodbRoute
  HtmlToJsxRoute: typeof HtmlToJsxRoute
  HtmlToPugRoute: typeof HtmlToPugRoute
  JsObjectToJsonRoute: typeof JsObjectToJsonRoute
  JsObjectToTypescriptRoute: typeof JsObjectToTypescriptRoute
  JsonSchemaToOpenapiSchemaRoute: typeof JsonSchemaToOpenapiSchemaRoute
  JsonSchemaToProtobufRoute: typeof JsonSchemaToProtobufRoute
  JsonSchemaToTsRoute: typeof JsonSchemaToTsRoute
  JsonSchemaToTypescriptRoute: typeof JsonSchemaToTypescriptRoute
  JsonSchemaToZodRoute: typeof JsonSchemaToZodRoute
  JsonToBigQueryRoute: typeof JsonToBigQueryRoute
  JsonToFlowRoute: typeof JsonToFlowRoute
  JsonToFlowTypesRoute: typeof JsonToFlowTypesRoute
  JsonToGoRoute: typeof JsonToGoRoute
  JsonToGoBsonRoute: typeof JsonToGoBsonRoute
  JsonToGraphqlRoute: typeof JsonToGraphqlRoute
  JsonToIoTsRoute: typeof JsonToIoTsRoute
  JsonToJavaRoute: typeof JsonToJavaRoute
  JsonToJsdocRoute: typeof JsonToJsdocRoute
  JsonToJsonSchemaRoute: typeof JsonToJsonSchemaRoute
  JsonToKotlinRoute: typeof JsonToKotlinRoute
  JsonToMobxStateTreeRoute: typeof JsonToMobxStateTreeRoute
  JsonToMongooseRoute: typeof JsonToMongooseRoute
  JsonToMysqlRoute: typeof JsonToMysqlRoute
  JsonToProptypesRoute: typeof JsonToProptypesRoute
  JsonToRustSerdeRoute: typeof JsonToRustSerdeRoute
  JsonToSarcasticRoute: typeof JsonToSarcasticRoute
  JsonToScalaCaseClassRoute: typeof JsonToScalaCaseClassRoute
  JsonToTomlRoute: typeof JsonToTomlRoute
  JsonToTsInterfaceRoute: typeof JsonToTsInterfaceRoute
  JsonToTypescriptRoute: typeof JsonToTypescriptRoute
  JsonToYamlRoute: typeof JsonToYamlRoute
  JsonToZodRoute: typeof JsonToZodRoute
  JsonldToCompactedRoute: typeof JsonldToCompactedRoute
  JsonldToExpandedRoute: typeof JsonldToExpandedRoute
  JsonldToFlattenedRoute: typeof JsonldToFlattenedRoute
  JsonldToFramedRoute: typeof JsonldToFramedRoute
  JsonldToNormalizedRoute: typeof JsonldToNormalizedRoute
  JsonldToNquadsRoute: typeof JsonldToNquadsRoute
  MarkdownToHtmlRoute: typeof MarkdownToHtmlRoute
  ObjectStylesToTemplateLiteralRoute: typeof ObjectStylesToTemplateLiteralRoute
  SvgToJsxRoute: typeof SvgToJsxRoute
  SvgToReactNativeRoute: typeof SvgToReactNativeRoute
  TomlToJsonRoute: typeof TomlToJsonRoute
  TomlToYamlRoute: typeof TomlToYamlRoute
  TypescriptToFlowRoute: typeof TypescriptToFlowRoute
  TypescriptToJavascriptRoute: typeof TypescriptToJavascriptRoute
  TypescriptToJsonSchemaRoute: typeof TypescriptToJsonSchemaRoute
  TypescriptToTypescriptDeclarationRoute: typeof TypescriptToTypescriptDeclarationRoute
  TypescriptToZodRoute: typeof TypescriptToZodRoute
  XmlToJsonRoute: typeof XmlToJsonRoute
  YamlToJsonRoute: typeof YamlToJsonRoute
  YamlToTomlRoute: typeof YamlToTomlRoute
  ApiFlowToJavascriptRoute: typeof ApiFlowToJavascriptRoute
  ApiFlowToTypescriptRoute: typeof ApiFlowToTypescriptRoute
  ApiHtmlToPugRoute: typeof ApiHtmlToPugRoute
  ApiJsonSchemaToOpenapiSchemaRoute: typeof ApiJsonSchemaToOpenapiSchemaRoute
  ApiTypescriptToFlowRoute: typeof ApiTypescriptToFlowRoute
  ApiTypescriptToJavascriptRoute: typeof ApiTypescriptToJavascriptRoute
  ApiTypescriptToJsonSchemaRoute: typeof ApiTypescriptToJsonSchemaRoute
  ApiTypescriptToZodRoute: typeof ApiTypescriptToZodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadence-to-go': {
      id: '/cadence-to-go'
      path: '/cadence-to-go'
      fullPath: '/cadence-to-go'
      preLoaderRoute: typeof CadenceToGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-to-js': {
      id: '/css-to-js'
      path: '/css-to-js'
      fullPath: '/css-to-js'
      preLoaderRoute: typeof CssToJsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-to-tailwind': {
      id: '/css-to-tailwind'
      path: '/css-to-tailwind'
      fullPath: '/css-to-tailwind'
      preLoaderRoute: typeof CssToTailwindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-to-javascript': {
      id: '/flow-to-javascript'
      path: '/flow-to-javascript'
      fullPath: '/flow-to-javascript'
      preLoaderRoute: typeof FlowToJavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-to-typescript': {
      id: '/flow-to-typescript'
      path: '/flow-to-typescript'
      fullPath: '/flow-to-typescript'
      preLoaderRoute: typeof FlowToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-to-typescript-declaration': {
      id: '/flow-to-typescript-declaration'
      path: '/flow-to-typescript-declaration'
      fullPath: '/flow-to-typescript-declaration'
      preLoaderRoute: typeof FlowToTypescriptDeclarationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-components': {
      id: '/graphql-to-components'
      path: '/graphql-to-components'
      fullPath: '/graphql-to-components'
      preLoaderRoute: typeof GraphqlToComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-flow': {
      id: '/graphql-to-flow'
      path: '/graphql-to-flow'
      fullPath: '/graphql-to-flow'
      preLoaderRoute: typeof GraphqlToFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-fragment-matcher': {
      id: '/graphql-to-fragment-matcher'
      path: '/graphql-to-fragment-matcher'
      fullPath: '/graphql-to-fragment-matcher'
      preLoaderRoute: typeof GraphqlToFragmentMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-introspection-json': {
      id: '/graphql-to-introspection-json'
      path: '/graphql-to-introspection-json'
      fullPath: '/graphql-to-introspection-json'
      preLoaderRoute: typeof GraphqlToIntrospectionJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-java': {
      id: '/graphql-to-java'
      path: '/graphql-to-java'
      fullPath: '/graphql-to-java'
      preLoaderRoute: typeof GraphqlToJavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-resolvers-signature': {
      id: '/graphql-to-resolvers-signature'
      path: '/graphql-to-resolvers-signature'
      fullPath: '/graphql-to-resolvers-signature'
      preLoaderRoute: typeof GraphqlToResolversSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-schema-ast': {
      id: '/graphql-to-schema-ast'
      path: '/graphql-to-schema-ast'
      fullPath: '/graphql-to-schema-ast'
      preLoaderRoute: typeof GraphqlToSchemaAstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-typescript': {
      id: '/graphql-to-typescript'
      path: '/graphql-to-typescript'
      fullPath: '/graphql-to-typescript'
      preLoaderRoute: typeof GraphqlToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql-to-typescript-mongodb': {
      id: '/graphql-to-typescript-mongodb'
      path: '/graphql-to-typescript-mongodb'
      fullPath: '/graphql-to-typescript-mongodb'
      preLoaderRoute: typeof GraphqlToTypescriptMongodbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-to-jsx': {
      id: '/html-to-jsx'
      path: '/html-to-jsx'
      fullPath: '/html-to-jsx'
      preLoaderRoute: typeof HtmlToJsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-to-pug': {
      id: '/html-to-pug'
      path: '/html-to-pug'
      fullPath: '/html-to-pug'
      preLoaderRoute: typeof HtmlToPugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js-object-to-json': {
      id: '/js-object-to-json'
      path: '/js-object-to-json'
      fullPath: '/js-object-to-json'
      preLoaderRoute: typeof JsObjectToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/js-object-to-typescript': {
      id: '/js-object-to-typescript'
      path: '/js-object-to-typescript'
      fullPath: '/js-object-to-typescript'
      preLoaderRoute: typeof JsObjectToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema-to-openapi-schema': {
      id: '/json-schema-to-openapi-schema'
      path: '/json-schema-to-openapi-schema'
      fullPath: '/json-schema-to-openapi-schema'
      preLoaderRoute: typeof JsonSchemaToOpenapiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema-to-protobuf': {
      id: '/json-schema-to-protobuf'
      path: '/json-schema-to-protobuf'
      fullPath: '/json-schema-to-protobuf'
      preLoaderRoute: typeof JsonSchemaToProtobufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema-to-ts': {
      id: '/json-schema-to-ts'
      path: '/json-schema-to-ts'
      fullPath: '/json-schema-to-ts'
      preLoaderRoute: typeof JsonSchemaToTsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema-to-typescript': {
      id: '/json-schema-to-typescript'
      path: '/json-schema-to-typescript'
      fullPath: '/json-schema-to-typescript'
      preLoaderRoute: typeof JsonSchemaToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-schema-to-zod': {
      id: '/json-schema-to-zod'
      path: '/json-schema-to-zod'
      fullPath: '/json-schema-to-zod'
      preLoaderRoute: typeof JsonSchemaToZodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-big-query': {
      id: '/json-to-big-query'
      path: '/json-to-big-query'
      fullPath: '/json-to-big-query'
      preLoaderRoute: typeof JsonToBigQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-flow': {
      id: '/json-to-flow'
      path: '/json-to-flow'
      fullPath: '/json-to-flow'
      preLoaderRoute: typeof JsonToFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-flow-types': {
      id: '/json-to-flow-types'
      path: '/json-to-flow-types'
      fullPath: '/json-to-flow-types'
      preLoaderRoute: typeof JsonToFlowTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-go': {
      id: '/json-to-go'
      path: '/json-to-go'
      fullPath: '/json-to-go'
      preLoaderRoute: typeof JsonToGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-go-bson': {
      id: '/json-to-go-bson'
      path: '/json-to-go-bson'
      fullPath: '/json-to-go-bson'
      preLoaderRoute: typeof JsonToGoBsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-graphql': {
      id: '/json-to-graphql'
      path: '/json-to-graphql'
      fullPath: '/json-to-graphql'
      preLoaderRoute: typeof JsonToGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-io-ts': {
      id: '/json-to-io-ts'
      path: '/json-to-io-ts'
      fullPath: '/json-to-io-ts'
      preLoaderRoute: typeof JsonToIoTsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-java': {
      id: '/json-to-java'
      path: '/json-to-java'
      fullPath: '/json-to-java'
      preLoaderRoute: typeof JsonToJavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-jsdoc': {
      id: '/json-to-jsdoc'
      path: '/json-to-jsdoc'
      fullPath: '/json-to-jsdoc'
      preLoaderRoute: typeof JsonToJsdocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-json-schema': {
      id: '/json-to-json-schema'
      path: '/json-to-json-schema'
      fullPath: '/json-to-json-schema'
      preLoaderRoute: typeof JsonToJsonSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-kotlin': {
      id: '/json-to-kotlin'
      path: '/json-to-kotlin'
      fullPath: '/json-to-kotlin'
      preLoaderRoute: typeof JsonToKotlinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-mobx-state-tree': {
      id: '/json-to-mobx-state-tree'
      path: '/json-to-mobx-state-tree'
      fullPath: '/json-to-mobx-state-tree'
      preLoaderRoute: typeof JsonToMobxStateTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-mongoose': {
      id: '/json-to-mongoose'
      path: '/json-to-mongoose'
      fullPath: '/json-to-mongoose'
      preLoaderRoute: typeof JsonToMongooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-mysql': {
      id: '/json-to-mysql'
      path: '/json-to-mysql'
      fullPath: '/json-to-mysql'
      preLoaderRoute: typeof JsonToMysqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-proptypes': {
      id: '/json-to-proptypes'
      path: '/json-to-proptypes'
      fullPath: '/json-to-proptypes'
      preLoaderRoute: typeof JsonToProptypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-rust-serde': {
      id: '/json-to-rust-serde'
      path: '/json-to-rust-serde'
      fullPath: '/json-to-rust-serde'
      preLoaderRoute: typeof JsonToRustSerdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-sarcastic': {
      id: '/json-to-sarcastic'
      path: '/json-to-sarcastic'
      fullPath: '/json-to-sarcastic'
      preLoaderRoute: typeof JsonToSarcasticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-scala-case-class': {
      id: '/json-to-scala-case-class'
      path: '/json-to-scala-case-class'
      fullPath: '/json-to-scala-case-class'
      preLoaderRoute: typeof JsonToScalaCaseClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-toml': {
      id: '/json-to-toml'
      path: '/json-to-toml'
      fullPath: '/json-to-toml'
      preLoaderRoute: typeof JsonToTomlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-ts-interface': {
      id: '/json-to-ts-interface'
      path: '/json-to-ts-interface'
      fullPath: '/json-to-ts-interface'
      preLoaderRoute: typeof JsonToTsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-typescript': {
      id: '/json-to-typescript'
      path: '/json-to-typescript'
      fullPath: '/json-to-typescript'
      preLoaderRoute: typeof JsonToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-yaml': {
      id: '/json-to-yaml'
      path: '/json-to-yaml'
      fullPath: '/json-to-yaml'
      preLoaderRoute: typeof JsonToYamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-zod': {
      id: '/json-to-zod'
      path: '/json-to-zod'
      fullPath: '/json-to-zod'
      preLoaderRoute: typeof JsonToZodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-compacted': {
      id: '/jsonld-to-compacted'
      path: '/jsonld-to-compacted'
      fullPath: '/jsonld-to-compacted'
      preLoaderRoute: typeof JsonldToCompactedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-expanded': {
      id: '/jsonld-to-expanded'
      path: '/jsonld-to-expanded'
      fullPath: '/jsonld-to-expanded'
      preLoaderRoute: typeof JsonldToExpandedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-flattened': {
      id: '/jsonld-to-flattened'
      path: '/jsonld-to-flattened'
      fullPath: '/jsonld-to-flattened'
      preLoaderRoute: typeof JsonldToFlattenedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-framed': {
      id: '/jsonld-to-framed'
      path: '/jsonld-to-framed'
      fullPath: '/jsonld-to-framed'
      preLoaderRoute: typeof JsonldToFramedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-normalized': {
      id: '/jsonld-to-normalized'
      path: '/jsonld-to-normalized'
      fullPath: '/jsonld-to-normalized'
      preLoaderRoute: typeof JsonldToNormalizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonld-to-nquads': {
      id: '/jsonld-to-nquads'
      path: '/jsonld-to-nquads'
      fullPath: '/jsonld-to-nquads'
      preLoaderRoute: typeof JsonldToNquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-to-html': {
      id: '/markdown-to-html'
      path: '/markdown-to-html'
      fullPath: '/markdown-to-html'
      preLoaderRoute: typeof MarkdownToHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-styles-to-template-literal': {
      id: '/object-styles-to-template-literal'
      path: '/object-styles-to-template-literal'
      fullPath: '/object-styles-to-template-literal'
      preLoaderRoute: typeof ObjectStylesToTemplateLiteralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-to-jsx': {
      id: '/svg-to-jsx'
      path: '/svg-to-jsx'
      fullPath: '/svg-to-jsx'
      preLoaderRoute: typeof SvgToJsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-to-react-native': {
      id: '/svg-to-react-native'
      path: '/svg-to-react-native'
      fullPath: '/svg-to-react-native'
      preLoaderRoute: typeof SvgToReactNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toml-to-json': {
      id: '/toml-to-json'
      path: '/toml-to-json'
      fullPath: '/toml-to-json'
      preLoaderRoute: typeof TomlToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toml-to-yaml': {
      id: '/toml-to-yaml'
      path: '/toml-to-yaml'
      fullPath: '/toml-to-yaml'
      preLoaderRoute: typeof TomlToYamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typescript-to-flow': {
      id: '/typescript-to-flow'
      path: '/typescript-to-flow'
      fullPath: '/typescript-to-flow'
      preLoaderRoute: typeof TypescriptToFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typescript-to-javascript': {
      id: '/typescript-to-javascript'
      path: '/typescript-to-javascript'
      fullPath: '/typescript-to-javascript'
      preLoaderRoute: typeof TypescriptToJavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typescript-to-json-schema': {
      id: '/typescript-to-json-schema'
      path: '/typescript-to-json-schema'
      fullPath: '/typescript-to-json-schema'
      preLoaderRoute: typeof TypescriptToJsonSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typescript-to-typescript-declaration': {
      id: '/typescript-to-typescript-declaration'
      path: '/typescript-to-typescript-declaration'
      fullPath: '/typescript-to-typescript-declaration'
      preLoaderRoute: typeof TypescriptToTypescriptDeclarationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typescript-to-zod': {
      id: '/typescript-to-zod'
      path: '/typescript-to-zod'
      fullPath: '/typescript-to-zod'
      preLoaderRoute: typeof TypescriptToZodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-to-json': {
      id: '/xml-to-json'
      path: '/xml-to-json'
      fullPath: '/xml-to-json'
      preLoaderRoute: typeof XmlToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaml-to-json': {
      id: '/yaml-to-json'
      path: '/yaml-to-json'
      fullPath: '/yaml-to-json'
      preLoaderRoute: typeof YamlToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaml-to-toml': {
      id: '/yaml-to-toml'
      path: '/yaml-to-toml'
      fullPath: '/yaml-to-toml'
      preLoaderRoute: typeof YamlToTomlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flow-to-javascript': {
      id: '/api/flow-to-javascript'
      path: '/api/flow-to-javascript'
      fullPath: '/api/flow-to-javascript'
      preLoaderRoute: typeof ApiFlowToJavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flow-to-typescript': {
      id: '/api/flow-to-typescript'
      path: '/api/flow-to-typescript'
      fullPath: '/api/flow-to-typescript'
      preLoaderRoute: typeof ApiFlowToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/html-to-pug': {
      id: '/api/html-to-pug'
      path: '/api/html-to-pug'
      fullPath: '/api/html-to-pug'
      preLoaderRoute: typeof ApiHtmlToPugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/json-schema-to-openapi-schema': {
      id: '/api/json-schema-to-openapi-schema'
      path: '/api/json-schema-to-openapi-schema'
      fullPath: '/api/json-schema-to-openapi-schema'
      preLoaderRoute: typeof ApiJsonSchemaToOpenapiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typescript-to-flow': {
      id: '/api/typescript-to-flow'
      path: '/api/typescript-to-flow'
      fullPath: '/api/typescript-to-flow'
      preLoaderRoute: typeof ApiTypescriptToFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typescript-to-javascript': {
      id: '/api/typescript-to-javascript'
      path: '/api/typescript-to-javascript'
      fullPath: '/api/typescript-to-javascript'
      preLoaderRoute: typeof ApiTypescriptToJavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typescript-to-json-schema': {
      id: '/api/typescript-to-json-schema'
      path: '/api/typescript-to-json-schema'
      fullPath: '/api/typescript-to-json-schema'
      preLoaderRoute: typeof ApiTypescriptToJsonSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typescript-to-zod': {
      id: '/api/typescript-to-zod'
      path: '/api/typescript-to-zod'
      fullPath: '/api/typescript-to-zod'
      preLoaderRoute: typeof ApiTypescriptToZodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadenceToGoRoute: CadenceToGoRoute,
  CssToJsRoute: CssToJsRoute,
  CssToTailwindRoute: CssToTailwindRoute,
  FlowToJavascriptRoute: FlowToJavascriptRoute,
  FlowToTypescriptRoute: FlowToTypescriptRoute,
  FlowToTypescriptDeclarationRoute: FlowToTypescriptDeclarationRoute,
  GraphqlToComponentsRoute: GraphqlToComponentsRoute,
  GraphqlToFlowRoute: GraphqlToFlowRoute,
  GraphqlToFragmentMatcherRoute: GraphqlToFragmentMatcherRoute,
  GraphqlToIntrospectionJsonRoute: GraphqlToIntrospectionJsonRoute,
  GraphqlToJavaRoute: GraphqlToJavaRoute,
  GraphqlToResolversSignatureRoute: GraphqlToResolversSignatureRoute,
  GraphqlToSchemaAstRoute: GraphqlToSchemaAstRoute,
  GraphqlToTypescriptRoute: GraphqlToTypescriptRoute,
  GraphqlToTypescriptMongodbRoute: GraphqlToTypescriptMongodbRoute,
  HtmlToJsxRoute: HtmlToJsxRoute,
  HtmlToPugRoute: HtmlToPugRoute,
  JsObjectToJsonRoute: JsObjectToJsonRoute,
  JsObjectToTypescriptRoute: JsObjectToTypescriptRoute,
  JsonSchemaToOpenapiSchemaRoute: JsonSchemaToOpenapiSchemaRoute,
  JsonSchemaToProtobufRoute: JsonSchemaToProtobufRoute,
  JsonSchemaToTsRoute: JsonSchemaToTsRoute,
  JsonSchemaToTypescriptRoute: JsonSchemaToTypescriptRoute,
  JsonSchemaToZodRoute: JsonSchemaToZodRoute,
  JsonToBigQueryRoute: JsonToBigQueryRoute,
  JsonToFlowRoute: JsonToFlowRoute,
  JsonToFlowTypesRoute: JsonToFlowTypesRoute,
  JsonToGoRoute: JsonToGoRoute,
  JsonToGoBsonRoute: JsonToGoBsonRoute,
  JsonToGraphqlRoute: JsonToGraphqlRoute,
  JsonToIoTsRoute: JsonToIoTsRoute,
  JsonToJavaRoute: JsonToJavaRoute,
  JsonToJsdocRoute: JsonToJsdocRoute,
  JsonToJsonSchemaRoute: JsonToJsonSchemaRoute,
  JsonToKotlinRoute: JsonToKotlinRoute,
  JsonToMobxStateTreeRoute: JsonToMobxStateTreeRoute,
  JsonToMongooseRoute: JsonToMongooseRoute,
  JsonToMysqlRoute: JsonToMysqlRoute,
  JsonToProptypesRoute: JsonToProptypesRoute,
  JsonToRustSerdeRoute: JsonToRustSerdeRoute,
  JsonToSarcasticRoute: JsonToSarcasticRoute,
  JsonToScalaCaseClassRoute: JsonToScalaCaseClassRoute,
  JsonToTomlRoute: JsonToTomlRoute,
  JsonToTsInterfaceRoute: JsonToTsInterfaceRoute,
  JsonToTypescriptRoute: JsonToTypescriptRoute,
  JsonToYamlRoute: JsonToYamlRoute,
  JsonToZodRoute: JsonToZodRoute,
  JsonldToCompactedRoute: JsonldToCompactedRoute,
  JsonldToExpandedRoute: JsonldToExpandedRoute,
  JsonldToFlattenedRoute: JsonldToFlattenedRoute,
  JsonldToFramedRoute: JsonldToFramedRoute,
  JsonldToNormalizedRoute: JsonldToNormalizedRoute,
  JsonldToNquadsRoute: JsonldToNquadsRoute,
  MarkdownToHtmlRoute: MarkdownToHtmlRoute,
  ObjectStylesToTemplateLiteralRoute: ObjectStylesToTemplateLiteralRoute,
  SvgToJsxRoute: SvgToJsxRoute,
  SvgToReactNativeRoute: SvgToReactNativeRoute,
  TomlToJsonRoute: TomlToJsonRoute,
  TomlToYamlRoute: TomlToYamlRoute,
  TypescriptToFlowRoute: TypescriptToFlowRoute,
  TypescriptToJavascriptRoute: TypescriptToJavascriptRoute,
  TypescriptToJsonSchemaRoute: TypescriptToJsonSchemaRoute,
  TypescriptToTypescriptDeclarationRoute:
    TypescriptToTypescriptDeclarationRoute,
  TypescriptToZodRoute: TypescriptToZodRoute,
  XmlToJsonRoute: XmlToJsonRoute,
  YamlToJsonRoute: YamlToJsonRoute,
  YamlToTomlRoute: YamlToTomlRoute,
  ApiFlowToJavascriptRoute: ApiFlowToJavascriptRoute,
  ApiFlowToTypescriptRoute: ApiFlowToTypescriptRoute,
  ApiHtmlToPugRoute: ApiHtmlToPugRoute,
  ApiJsonSchemaToOpenapiSchemaRoute: ApiJsonSchemaToOpenapiSchemaRoute,
  ApiTypescriptToFlowRoute: ApiTypescriptToFlowRoute,
  ApiTypescriptToJavascriptRoute: ApiTypescriptToJavascriptRoute,
  ApiTypescriptToJsonSchemaRoute: ApiTypescriptToJsonSchemaRoute,
  ApiTypescriptToZodRoute: ApiTypescriptToZodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
